spring:
  application:
    name: product-catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/product_catalog
    username: postgres
    password: adm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method